#!/usr/bin/env python3
"""Generate the Meow P scene-act catalog.

    python3 scripts/gen_reddit_catalog.py
    python3 scripts/gen_reddit_catalog.py --out /path/to/dir

Writes reddit-pose-catalog.json and .md. Default --out is the local
anchor5/ lab (gitignored). Tables in this file are the source; the
json/md are generated.

A scene is composed as:
  configuration × pose × contact × act × finish × movement × camera [× overlay]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "anchor5"

README = [
    "Adult 18+ only. Scene vocabulary for Meow P: poses, acts, configs, finishes, movement.",
    "A scene is configuration × pose × contact × act × finish × movement × camera [× overlay].",
    "topic id is the primitive. aliases map every common porn name onto one id.",
    "Extract skeleton/depth/camera from a still or GIF hold-frame. Discard pixels.",
    "Never use as image1 or as a person-plate in image2.",
]

HARD_EXCLUDES = [
    "teen / barely-legal / college-as-underage / jailbait / loli / young-girls packaging",
    "school tropes and youthful uniforms even on adult-named subs",
    "any face that reads under-18",
    "incest",
    "personals",
    "casting genres used as acts (MILF, PAWG, ethnicity, amateur, studio) — those are cast, not geometry",
]

# Live Firefox session, 2026-08-15. 1150 subscribed (1146 nsfw). 40 excluded
# (teen/youthful). Full working list: reddit-subscribed.json (shuffled, no excludes).
PROFILE_ACTIVITY = {
    "user": "SouthFloridaCouple",
    "subscriptions_public": True,
    "source": "old.reddit.com/subreddits/mine/subscriber.json via Firefox cookies, 2026-08-15",
    "total_subscribed": 1150,
    "excluded": 40,
    "working_list": "anchor5/reddit-subscribed.json",
    "pose_useful": [
        {"sub": "FFMFucklick", "maps_to": "fucklicking", "why": "Named fucklick feed. During-sex lick, not cleanup."},
        {"sub": "CreamPieFlowingOut", "maps_to": "creampie_flow", "why": "Exact leak/push-out."},
        {"sub": "squirting", "maps_to": "squirt", "why": "Main squirt. Split seated/lying/kneeling/anal from hold frames."},
        {"sub": "GushingGirls", "maps_to": "squirt", "why": "Gush stills+clips."},
        {"sub": "grool", "maps_to": "squirt", "why": "Wetness, not jet."},
        {"sub": "CowgirlRiders", "maps_to": "cowgirl", "why": "Dedicated ride. Search reverse in titles."},
        {"sub": "DoggyStyle", "maps_to": "doggy", "why": "High-volume doggy."},
        {"sub": "Doggystyle_NSFW", "maps_to": "doggy", "why": "Act-clean doggy gifs."},
        {"sub": "facedownassup", "maps_to": "face_down_ass_up", "why": "FDAU."},
        {"sub": "AssUpFaceDown", "maps_to": "face_down_ass_up", "why": "FDAU sibling."},
        {"sub": "pronebone", "maps_to": "pronebone", "why": "Prone."},
        {"sub": "pronebone_spitroast", "maps_to": "spit_roast", "why": "Prone + spit roast together."},
        {"sub": "Onechick2dicks", "maps_to": "spit_roast", "why": "Oral+rear two-partner line."},
        {"sub": "SpitRoastedGW", "maps_to": "spit_roast", "why": "Amateur spit roast."},
        {"sub": "SensualMFM", "maps_to": "mfm", "why": "MFM, no MM required."},
        {"sub": "SensualMMF", "maps_to": "mmf", "why": "MMF / bi contact."},
        {"sub": "OnHerBack", "maps_to": "missionary", "why": "Supine sheet."},
        {"sub": "Anal_Missionary", "maps_to": "missionary", "why": "Missionary + anal contact."},
        {"sub": "Pussy_From_Behind", "maps_to": "bent_over_lookback", "why": "Rear vulva / look-back."},
        {"sub": "rearpussy", "maps_to": "rear_anatomy", "why": "From-behind vulva/perineum stills. Anatomy after pose QC."},
        {"sub": "GodPussyv2", "maps_to": "vulva_closeup", "why": "Live godpussy. Shape/labia samples, never image2."},
        {"sub": "PussiesCloseUp", "maps_to": "vulva_closeup", "why": "Shaved close-up vulva."},
        {"sub": "LoveThyLabia", "maps_to": "vulva_closeup", "why": "Labia shape library."},
        {"sub": "GodAsshole", "maps_to": "anus_closeup", "why": "Anus + tail-origin samples."},
        {"sub": "asshole_closeup", "maps_to": "anus_closeup", "why": "Tight anus stills."},
        {"sub": "NSFW_Plowcam", "maps_to": "plowcam", "why": "Floor camera."},
        {"sub": "facesitting", "maps_to": "facesit", "why": "Sit-on-face."},
        {"sub": "FacesittingHub", "maps_to": "facesit", "why": "Second facesit dump."},
        {"sub": "Eating_Pussy_GIFs", "maps_to": "cunnilingus", "why": "Oral-on-her motion."},
        {"sub": "LickableStarfish", "maps_to": "rim", "why": "Rimming."},
        {"sub": "scissoring", "maps_to": "scissoring", "why": "Girl-on-girl lock."},
        {"sub": "lesbians", "maps_to": "lesbian", "why": "Parent girl-on-girl."},
        {"sub": "GirlsWithGirls", "maps_to": "lesbian", "why": "Second lesbian dump."},
        {"sub": "gangbang", "maps_to": "gangbang", "why": "GB."},
        {"sub": "GangbangChicks", "maps_to": "gangbang", "why": "Woman-centered GB."},
        {"sub": "AirTight", "maps_to": "airtight", "why": "Three holes."},
        {"sub": "CreampieCleanUp", "maps_to": "creampie_cleanup", "why": "Aftermath lick."},
        {"sub": "holdthemoan", "maps_to": "standing_sex", "why": "Standing/wall/quiet."},
        {"sub": "freeuse", "maps_to": "freeuse", "why": "Mid-task."},
        {"sub": "SheLikesItRough", "maps_to": "rough", "why": "Pin/fold overlay."},
    ],
    "not_pose": [
        "Personals / r4r / club ads are not pose sources.",
        "Pussy-macro / asshole-macro subs are anatomy_sample AFTER pose QC. Never as image2 or a person-plate.",
        "Ethnicity/cast dumps are not geometry.",
        "40 teen/youthful-named subs were dropped from the working list.",
    ],
}

# Intra-topic variants. A scene row can be topic + variant.
# Example: squirt + seated, squirt + anal.
VARIANTS = {
    "squirt": ["seated", "lying_supine", "kneeling", "all_fours", "standing", "anal", "solo_toy"],
    "squirt_while_fucked": ["doggy", "cowgirl", "missionary", "anal"],
    "creampie_flow": ["doggy", "missionary", "standing", "anal", "push_out"],
    "cowgirl": ["upright", "lean_forward", "grind"],
    "reverse_cowgirl": ["upright", "look_back", "lean_forward"],
    "doggy": ["hands_down", "elbows_down", "look_back", "anal"],
    "missionary": ["legs_wrapped", "legs_up", "legs_on_shoulders"],
    "facesit": ["face_forward", "look_back", "smother"],
    "spit_roast": ["doggy_oral", "standing_oral", "prone_oral"],
    "lesbian_strap": ["doggy", "missionary", "standing"],
    "gangbang": ["doggy", "missionary", "cowgirl", "spit_roast"],
    "rear_anatomy": ["all_fours", "look_back", "spread", "panties_aside"],
    "vulva_closeup": ["innie", "outie", "spread"],
    "anus_closeup": ["closed", "spread", "tail_origin"],
}

# ---------------------------------------------------------------------------
# Aliases: any name a storyboard or tube tag might use → distinct topic id
# ---------------------------------------------------------------------------
ALIASES = {
    # configs
    "1on1": "pair", "couple": "pair", "mf": "pair", "fm": "pair",
    "mfm threesome": "mfm", "two men one woman": "mfm", "double team": "mfm",
    "mmf threesome": "mmf", "bisexual threesome": "mmf",
    "ffm threesome": "ffm", "two girls one guy": "ffm",
    "fmf threesome": "fmf", "man in the middle": "fmf",
    "fff": "fff", "lesbian threesome": "fff", "three girls": "fff",
    "4some": "foursome", "fourgy": "foursome", "foursome": "foursome",
    "mmmf": "mmmf", "three men one woman": "mmmf",
    "fffm": "fffm", "reverse gangbang": "reverse_gangbang",
    "mfmf": "mfmf", "two couples": "mfmf",
    "ffff": "fff",  # reduce: four women is lesbian group, use lesbian_gangbang or orgy
    "gb": "gangbang", "gang bang": "gangbang", "bang": "gangbang",
    "pulling a train": "train", "run a train": "train",
    "groupsex": "orgy", "group sex": "orgy", "swingers pile": "orgy",
    "circle jerk": "blowbang",  # not her sheet
    # poses
    "doggystyle": "doggy", "doggy style": "doggy", "from behind all fours": "doggy",
    "stallion": "doggy", "leapfrog": "face_down_ass_up", "bulldog": "doggy",
    "fdau": "face_down_ass_up", "face down ass up": "face_down_ass_up",
    "chest down hips up": "face_down_ass_up",
    "flat iron": "pronebone", "prone": "pronebone", "lying doggy": "pronebone",
    "man on top": "missionary", "missionary plus": "missionary", "cat": "missionary",
    "coital alignment": "missionary", "stopperage": "mating_press",
    "folded missionary": "mating_press",
    "viennese oyster": "legs_over_head", "legs behind head": "legs_over_head",
    "woman on top": "cowgirl", "girl on top": "cowgirl", "riding": "cowgirl",
    "cowperson": "cowgirl", "asian cowgirl": "squat_ride", "squat cowgirl": "squat_ride",
    "reverse missionary": "cowgirl",
    "lotus flower": "lotus", "yab yum": "lotus", "pounding on the spot": "lotus",
    "lap sit": "lotus",
    "spoons": "spoon", "spooning": "spoon",
    "side fuck": "spoon",
    "scissors hetero": "side_scissor", "pretzel": "side_scissor",
    "edge of bed": "butterfly", "hips on edge": "butterfly",
    "suspended congress": "lift_carry", "ekiben": "lift_carry", "standing carry": "lift_carry",
    "reverse ekiben": "lift_carry",
    "bodyguard": "standing_behind", "standing doggy": "standing_behind",
    "from behind standing": "standing_behind",
    "against a wall": "wall_pin", "wall sex": "wall_pin",
    "tabletop": "furniture_edge", "kitchen counter": "furniture_edge",
    "over the table": "furniture_edge", "bent over furniture": "furniture_edge",
    "look back": "bent_over_lookback", "bent over": "bent_over_lookback",
    "rear pussy": "rear_anatomy", "rearpussy": "rear_anatomy",
    "pussy from behind": "rear_anatomy",
    "god pussy": "vulva_closeup", "godpussy": "vulva_closeup",
    "labia": "vulva_closeup", "innie": "vulva_closeup",
    "asshole closeup": "anus_closeup", "god asshole": "anus_closeup",
    "queening": "facesit", "facesitting": "facesit", "sit on face": "facesit",
    "69": "sixty_nine", "sixtynine": "sixty_nine",
    "on her knees": "kneel_oral", "fellatio kneel": "kneel_oral",
    "pile driver": "piledriver", "rusty bike pump": "piledriver",
    "nelson": "full_nelson",
    "t-square": "t_square", "tsquare": "t_square",
    "present": "all_fours", "crawl": "all_fours",
    "spread eagle": "legs_spread", "spreading": "legs_spread",
    # contact / acts
    "bj": "blowjob", "fellatio": "blowjob", "blow job": "blowjob",
    "irrumatio": "deepthroat", "facefuck": "deepthroat", "throat fuck": "deepthroat",
    "eating pussy": "cunnilingus", "pussy licking": "cunnilingus", "muff dive": "cunnilingus",
    "rimming": "rim", "anilingus": "rim", "rimjob": "rim", "tossed salad": "rim",
    "analingus": "rim",
    "hand job": "handjob", "hj": "handjob",
    "fingering": "fingering", "digit": "fingering",
    "titfuck": "titfuck", "titty fuck": "titfuck", "paizuri": "titfuck",
    "mammary intercourse": "titfuck",
    "thighjob": "thighjob", "intercrural": "thighjob",
    "footjob": "footjob", "fj": "footjob",
    "tribbing": "scissoring", "tribadism": "scissoring", "trib": "scissoring",
    "strap-on": "lesbian_strap", "strapon": "lesbian_strap",
    "peg": "pegging",
    "split roast": "spit_roast", "spitroast": "spit_roast", "chinese finger trap": "spit_roast",
    "eiffel tower": "spit_roast",
    "double team rear": "sandwich",
    "dp": "double_penetration", "double stuff": "double_penetration",
    "dvp": "double_vaginal", "double vaginal": "double_vaginal",
    "dap": "double_anal", "double anal": "double_anal",
    "tp": "triple_penetration", "triple": "triple_penetration",
    "atm": "ass_to_mouth", "ass to mouth": "ass_to_mouth",
    "snowball": "snowball",
    "cuck lick": "creampie_cleanup", "cleanup": "creampie_cleanup",
    "licked while fucked": "fucklicking", "cucklicking": "fucklicking",
    "ffmfucklick": "fucklicking", "fuck lick": "fucklicking",
    "on her back": "missionary", "onherback": "missionary",
    "ass up face down": "face_down_ass_up", "assupfacedown": "face_down_ass_up",
    "one chick 2 dicks": "spit_roast", "onechick2dicks": "spit_roast",
    "lickable starfish": "rim", "eating ass": "rim",
    "plowcam": "plowcam", "nsfw_plowcam": "plowcam",
    "girls with girls": "lesbian",
    "groolstrings": "squirt",
    "lucky pierre": "mmf",
    "369": "threesome_369",
    "double cowgirl": "double_cowgirl",
    "daisy chain": "daisy_chain",
    # finish
    "internal": "creampie", "creampied": "creampie", "don't pull out": "creampie",
    "leaking creampie": "creampie_flow", "flowing out": "creampie_flow",
    "pushing it out": "creampie_flow", "creampie drip": "creampie_flow",
    "anal creampie": "anal_creampie",
    "cumshot face": "facial", "facials": "facial",
    "body shot": "body_cum",
    "throat pie": "throatpie", "oral creampie": "throatpie",
    "female ejaculation": "squirt", "gush": "squirt", "squirting": "squirt",
    "breeding": "breeding_supine",
    "gaping": "gape",
    # movement / camera
    "when it goes in": "insertion",
    "plow cam": "plowcam", "under camera": "plowcam",
    "pov": "pov",
    # overlay
    "yiff": "anthro", "furry": "anthro",
    "used": "freeuse",
    "public sex": "public",
    "bdsm": "bondage", "tied": "bondage",
}

# ---------------------------------------------------------------------------
# Families + distinct topics
# tuple: (id, label, definition, skeleton, movement, hold_frame,
#         primary_sub, media, members, why, fallback|None)
# fallback = (sub, search, members, why) or None
# ---------------------------------------------------------------------------

def T(id, label, definition, skeleton, movement, hold, prim, media=None, members=None, why=None, fb=None):
    return dict(
        id=id, label=label, definition=definition, skeleton=skeleton,
        movement=movement, hold_frame=hold,
        primary=(prim, media, members, why),
        fallback=fb,
    )


FAMILIES = [
    # =====================================================================
    dict(
        id="configuration",
        label="Configuration — who is in the scene",
        note=(
            "Letter codes are gender of bodies, left-to-right is not order of acts. "
            "MFM ≠ MMF. FFM ≠ FMF. Count people first, then pick a pose and an act."
        ),
        topics=[
            T("solo", "Solo",
              "Her alone. Toys, hands, present, spread. No partner skeleton.",
              "One female body, complete.",
              "Self-touch, toy stroke, pose hold.",
              "Full body. Hands and toy readable.",
              "spreading", "still", None,
              "Cleanest solo expose. Not an act dump."),
            T("pair", "Pair / 1-on-1",
              "Her + one partner. Default if no group tag. Pose and act still required.",
              "Two bodies. She must be complete.",
              "Whatever the child pose is.",
              "Both bodies, her limbs complete.",
              "NSFW_GIF", "gif", "~3M",
              "Parent config. Do not search this — pick a pose."),
            T("mfm", "MFM",
              "Two men, one woman. No required male-male contact. The usual porn 'two guys one girl'.",
              "Her in the middle or on one of them. Two male bodies as props.",
              "Spit roast, sandwich, DP, or take-turns.",
              "Her full spine + both partners. Count three bodies.",
              "mfm", "mix", None,
              "Act-clean two-male one-female. Distinct from MMF."),
            T("mmf", "MMF",
              "Two men, one woman, with male-male contact (bisexual). Lucky Pierre lives here.",
              "Same count as MFM. One male is also receiving.",
              "One man fucks her while the other fucks him, or they contact each other.",
              "Her complete + the MM contact readable if that is the point.",
              "Threesome", "mix", "~1.1M",
              "Search MMF / bisexual. No large MMF-only pose sub."),
            T("ffm", "FFM",
              "Two women, one man. The women interact with each other and with him.",
              "Two female skeletons + one male. Girl-girl contact is required for this id.",
              "Double cowgirl, one rides / one sits on his face, or they kiss/lick while he fucks one.",
              "Both women complete. If the women never touch, it is FMF.",
              "Threesome", "mix", "~1.1M",
              "Search FFM. Largest mixed threesome feed."),
            T("fmf", "FMF",
              "Two women, one man, man in the middle. Women primarily on him, little girl-girl.",
              "He is the hub. Each woman occupies one end (mouth / lap / ride).",
              "One rides, one on his face or cock. Parallel, not scissoring.",
              "Both women + him. Women may not touch each other.",
              "Threesome", "mix", "~1.1M",
              "Search FMF or 'man in the middle'. Distinct from FFM."),
            T("fff", "FFF / lesbian threesome",
              "Three women. No male. Strap, scissor, sit, daisy chain.",
              "Three female skeletons.",
              "Two-on-one or a triangle.",
              "All three complete. She (Meow P) must be identifiable as one of them.",
              "lesbians", "mix", "~1.8M",
              "Search threesome / three inside r/lesbians."),
            T("foursome", "Foursome (parent)",
              "Exactly four people. Pick a child config (MFMF, MMMF, FFFM) for the sheet.",
              "Four bodies. She must still read.",
              "Two pairs, or 3-on-1, or a square.",
              "Her complete. Do not extract the pile.",
              "Xsome", "mix", "~667k",
              "Parent. Prefer a child id."),
            T("mfmf", "MFMF / two couples",
              "Two men, two women. Often two pairs side by side or a swap.",
              "Two female skeletons. Extract her, ignore the other woman if needed.",
              "Parallel pairs, or a four-way square / 469.",
              "Her pair readable.",
              "Xsome", "mix", "~667k",
              "Search foursome / two couples."),
            T("mmmf", "MMMF",
              "Three men, one woman. Gangbang-lite. Still one female sheet.",
              "Her + three males. Same extraction rule as gangbang.",
              "Spit roast + extra hands, or DP + oral.",
              "She fully readable. Extra men are clutter.",
              "gangbang", "gif/vid", "~726k",
              "Search foursome / 3 on 1. Count is the difference from gangbang."),
            T("fffm", "FFFM",
              "Three women, one man. Same bodies as reverse_gangbang at n=4.",
              "Three female + one male.",
              "He is the hub, or one woman is. Often reverse-gangbang tagged.",
              "Her complete among the women.",
              "Threesome", "mix", "~1.1M",
              "Search FFFM / reverse gangbang. Same topology as reverse_gangbang, smaller n."),
            T("gangbang", "Gangbang",
              "Many men, one woman, simultaneous. Crowd is noise. She is the sheet.",
              "One female skeleton, many extras.",
              "Many contacts at once. Hold a frame where she is not buried.",
              "Her full body. Ignore the crowd.",
              "gangbang", "gif/vid", "~726k",
              "Largest GB feed."),
            T("reverse_gangbang", "Reverse gangbang",
              "Many women, one man. She is one of the women — pick her skeleton.",
              "Several female bodies around one male.",
              "Take-turns ride / oral. She must be the readable one.",
              "Her complete. Do not extract a random extra.",
              "NSFW_GIF", "gif", "~3M",
              "Search reverse gangbang. No high-purity dedicated pose sub."),
            T("lesbian_gangbang", "Lesbian gangbang",
              "Many women on one woman. Strap, sit, lick, fist. No male.",
              "One receiving female + several female partners.",
              "Sequential or pile. Strap-doggy is the usual hold.",
              "The receiver (her) fully readable.",
              "lesbians", "mix", "~1.8M",
              "Search gangbang / group inside r/lesbians."),
            T("blowbang", "Blowbang",
              "Many partners around her, oral only. Kneel or face-up. Not a hip sheet.",
              "Kneel/sit, a circle of shafts.",
              "Turn from one to the next.",
              "Knees + torso + the circle. Skip face-only.",
              "blowbang", "mix", None,
              "Dedicated oral+crowd. Distinct from gangbang hips."),
            T("train", "Train / sequential",
              "One after another, not a pile. Pose may change per partner. Storyboard beats.",
              "Usually doggy or missionary, partner swaps.",
              "Sequence. Next beat is the swap.",
              "One partner locked. Not a simultaneous orgy.",
              "runatrain", "mix", None,
              "Defines sequential. Do not substitute r/gangbang."),
            T("orgy", "Orgy / group pile",
              "Many-to-many. No single hub. Full-room stills only.",
              "Many bodies. Only useful if she is isolated in frame.",
              "Chaos. Prefer one readable couple inside the room.",
              "A readable her, not the wide mess.",
              "Xsome", "mix", "~667k",
              "Largest 3+ dump. Crop-heavy."),
            T("daisy_chain", "Daisy chain",
              "A ring of oral. Each mouth on the next. Any gender mix.",
              "A circle of spines. Hard to extract one body.",
              "Lick around the ring.",
              "Her spine + the two contacts on her.",
              "NSFW_GIF", "gif", "~3M",
              "Search daisy chain. Rare clean full-body."),
        ],
    ),

    # =====================================================================
    dict(
        id="pose",
        label="Pose — her body geometry",
        note=(
            "One skeleton. Contact (vaginal/anal) is a separate axis — doggy is the pose, "
            "anal is the contact. Named variations that do not change the skeleton are aliases."
        ),
        topics=[
            T("all_fours", "All-fours / crawl / present",
              "Hands and knees, hips high, spine long. Partner optional.",
              "Four points on the ground, knees apart, head up or look-back.",
              "Crawl, weight shift, hip present.",
              "Peak hip present. Both knees and both hands visible.",
              "OnAllFours", "mix", None,
              "Pose-only. No partner required.",
              ("Doggystyle_NSFW", None, None, "Same skeleton with penetration.")),
            T("face_down_ass_up", "Face-down ass-up",
              "Chest and face down, hips up, knees apart, soles often toward camera. Not doggy.",
              "Torso folded, hips stacked over knees, arms forward or under chest.",
              "Hip lift, cheek spread, look-back optional.",
              "Hips highest, soles and cleft readable.",
              "facedownassup", "mix", None,
              "Dedicated FDAU. Closest to the couch photo.",
              ("nsfw_plowcam", None, None, "Low camera on the same hips.")),
            T("pronebone", "Pronebone",
              "Flat on her belly, hips pinned or slightly raised. Full spine on the bed.",
              "Prone, legs together or split, breasts smashed or spilled sideways.",
              "Short hip grind, not a bounce.",
              "Full spine + hips + his lock.",
              "pronebone", "gif", "~266k",
              "Dedicated prone. Large for a single-pose sub."),
            T("doggy", "Doggy",
              "All-fours plus rear penetration. Rear or 3/4 camera.",
              "Same as all_fours with a partner locked at the hips.",
              "Thrust cycle.",
              "Both knees planted, hips up, insertion readable.",
              "Doggystyle_NSFW", "gif", None,
              "Act-clean doggy.",
              ("anal", "doggy", "~2.2M", "Highest-traffic rear-entry dump.")),
            T("bent_over_lookback", "Bent-over / look-back",
              "Standing hinge at the hips, look over the shoulder.",
              "Hinge, legs straight or soft-knee, head rotated to camera.",
              "Push back, look-back hold.",
              "Face + hips in one frame.",
              "frombehind", "mix", None,
              "Rear camera standing or bent. Look-back lives here.",
              ("bentover", None, None, "Still-heavy standing hinge.")),
            T("standing_behind", "Standing from behind",
              "Both upright or she slightly hinged, he behind. Bodyguard / standing doggy.",
              "Two standing figures, her back to him, one leg up optional.",
              "Short standing thrusts.",
              "Head-to-feet, her back and his lock.",
              "holdthemoan", "gif", "~2.1M",
              "Largest standing/quiet/wall feed. Search standing / from behind."),
            T("standing_sex", "Standing face-to-face",
              "Both standing, facing each other. Full height, S-curve. Wall optional.",
              "Upright, one of her legs up optional, hands on him or a wall.",
              "Short thrusts. Hands brace.",
              "Head-to-feet.",
              "holdthemoan", "gif", "~2.1M",
              "Same high-traffic standing feed. Search standing / face to face."),
            T("wall_pin", "Wall pin",
              "Her back or chest against a wall, standing or one-leg-up.",
              "Upright, back or cheek to the wall, one knee high.",
              "Pin holds, short thrusts.",
              "Wall + her full height + the pin.",
              "holdthemoan", "gif", "~2.1M",
              "Search wall. Dedicated r/AgainstAWall is smaller."),
            T("furniture_edge", "Furniture edge / tabletop",
              "Hips on a lip (bed, table, counter), torso down or supine on the edge.",
              "Hips at the edge, legs hanging or wrapped, torso on the surface.",
              "He stands, she is the edge.",
              "Surface + hips + her torso.",
              "bentover", "still", None,
              "Standing hinge onto furniture. Search table / counter / edge."),
            T("lift_carry", "Lift / carry / ekiben",
              "He stands and holds her off the ground. Her legs around his waist, facing or reverse.",
              "Her feet off the floor, arms around his neck or hanging.",
              "Lift-thrust. Hard to hold a still.",
              "Both her feet visible off the ground.",
              "NSFW_GIF", "gif", "~3M",
              "Search ekiben / standing carry / lift. No large dedicated sub."),
            T("wheelbarrow", "Wheelbarrow",
              "She face-down, legs held, only hands (or nothing) on the ground.",
              "Inverted hinge, legs in his hands.",
              "Carry-thrust.",
              "Hands, hanging torso, held legs.",
              "NSFW_GIF", "gif", "~3M",
              "Search wheelbarrow. Dedicated sub is too small."),
            T("missionary", "Missionary",
              "On her back, legs up, wrapped, or open. He on top, facing her.",
              "Supine, knees toward chest or around him.",
              "Hip roll, legs pull back.",
              "Pelvis, both knees, torso. Not a crotch crop.",
              "Missionary", "gif", None,
              "Dedicated supine sex."),
            T("mating_press", "Mating press",
              "Folded missionary: knees to chest or shoulders, him on top, deep seat.",
              "Supine fold, knees at her shoulders, pelvis stacked.",
              "Short deep thrusts.",
              "Knees, shoulders, pelvis stacked.",
              "NSFW_GIF", "gif", "~3M",
              "Search mating press. Dedicated sub is small and anime-leaky."),
            T("legs_over_head", "Legs over head / Viennese oyster",
              "Supine, feet next to ears or crossed behind head. Extreme fold.",
              "Hips rolled, legs beside head, pelvis up.",
              "Hold the fold.",
              "Feet, head, and pelvis in one frame.",
              "NSFW_GIF", "gif", "~3M",
              "Search viennese oyster / legs behind head / legs over head."),
            T("butterfly", "Butterfly / edge hips-up",
              "Hips at the edge of a bed/table, legs up against him, he standing or kneeling.",
              "Supine on a lip, pelvis lifted, legs on his chest or shoulders.",
              "He stands and thrusts. She is still.",
              "Edge + lifted pelvis + both legs.",
              "Missionary", "gif", None,
              "Search butterfly / edge / legs up. Pose is missionary + furniture."),
            T("cowgirl", "Cowgirl",
              "She on top, facing him, doing the pumping. Knee plant, spine S-curve.",
              "Knees outside his hips, torso upright or lean-forward.",
              "Bounce / grind. She moves, he is still.",
              "Peak bounce, both knees planted, spine readable.",
              "SheFucksHim", "gif", "~2.5M",
              "Highest-traffic riding feed."),
            T("reverse_cowgirl", "Reverse cowgirl",
              "She rides facing away. Back, hips, look-back. Tail-aside analog.",
              "Knees planted, back to him, head rotated to camera or down.",
              "Bounce with look-back holds.",
              "Back + hips + look-back in one frame.",
              "ReverseCowgirl_NSFW", "gif", "~67k",
              "Reverse-only. Act-clean.",
              ("SheFucksHim", "reverse", "~2.5M", "If dedicated is thin.")),
            T("squat_ride", "Squat ride",
              "Cowgirl or reverse but she squats on the balls of her feet, not kneeling.",
              "Feet flat or on toes, knees high, hips over him.",
              "Up-down squat, not a kneel-bounce.",
              "Both feet visible, not knees-down.",
              "SheFucksHim", "gif", "~2.5M",
              "Search squat / asian cowgirl."),
            T("amazon", "Amazon",
              "He on his back, legs up. She straddles between his raised legs and fucks down.",
              "She upright or kneeling, his knees toward his chest, she between them.",
              "She thrusts. Power-top silhouette.",
              "His raised legs + her upright torso.",
              "NSFW_GIF", "gif", "~3M",
              "Search amazon position. Niche; no large dedicated sub."),
            T("lotus", "Lotus / lap sit",
              "He sits (cross-legged or on a chair). She sits in his lap, facing him, legs wrapped.",
              "Seated stack, her legs around his waist, chests close.",
              "Grind, not a bounce. Slow.",
              "Both seated, her wrap-legs readable.",
              "NSFW_GIF", "gif", "~3M",
              "Search lotus / lap / sitting. No large dedicated sub."),
            T("spoon", "Spoon",
              "Both on their side, facing the same direction. He behind.",
              "Two side-lying spines, her knees soft, his lock at her hips.",
              "Slow grind from behind.",
              "Both full side profiles.",
              "NSFW_GIF", "gif", "~3M",
              "Search spoon / spooning / side. Common pose, no huge dedicated sub."),
            T("side_scissor", "Side scissor / pretzel (hetero)",
              "She on her back or side, one leg scissored around him. Not lesbian tribbing.",
              "Her hips rotated, one leg over his hip or shoulder.",
              "Side-to-side thrust.",
              "The scissored leg + her torso.",
              "NSFW_GIF", "gif", "~3M",
              "Search pretzel / scissors. Distinct from scissoring."),
            T("t_square", "T-square",
              "She supine, knees up. He lies on his side perpendicular, hips under her arch.",
              "Her body is the top of the T, his the stem.",
              "Sideways thrust.",
              "The right angle of the two spines.",
              "NSFW_GIF", "gif", "~3M",
              "Search T-square. Rare. Skip if you cannot see both spines."),
            T("piledriver", "Piledriver",
              "Folded onto her neck/shoulders, hips up, penetration down from standing.",
              "Weight on shoulders/neck, hips stacked above head.",
              "Drop-thrust.",
              "Full fold. Rare clean full-body.",
              "NSFW_GIF", "gif", "~3M",
              "Search piledriver. Dedicated sub 404-prone."),
            T("full_nelson", "Full nelson",
              "Arms locked behind her head, legs up, penetration from behind or below.",
              "Arms hooked, knees high, torso upright or leaned.",
              "Lift and thrust.",
              "Locked arms + both legs + hips.",
              "NSFW_GIF", "gif", "~3M",
              "Search full nelson."),
            T("kneel_oral", "Kneeling oral",
              "She on her knees, look-up, mouth on a partner.",
              "Knees down, hips on heels or raised, neck extended.",
              "Bob. Hold the look-up.",
              "Knees + spine + face. Skip face-only.",
              "Blowjobs", "mix", "~2.4M",
              "Largest oral feed."),
            T("deepthroat", "Deepthroat pose",
              "Head–neck–torso under load. Throat pose, not a cute BJ still.",
              "Kneel or supine, neck long, jaw open, torso in frame.",
              "Hold at full seat.",
              "Neck + torso + knees.",
              "deepthroat", "gif", "~1.5M",
              "Dedicated. High volume."),
            T("facesit", "Facesitting / queening",
              "She sits on a face. Knee plant, hip drop, look-down or look-back.",
              "Knees beside a head, hips dropped, torso upright or lean.",
              "Grind / sit-hold.",
              "Both knees, hips, her torso.",
              "facesitting", "mix", None,
              "Dedicated sit-on-face."),
            T("sixty_nine", "69",
              "Mutual oral. Two-body stack, opposite directions.",
              "Two spines, her on top or side.",
              "Lick cycle. Hold a still stack.",
              "Her spine + hips. Skip if she is a head crop.",
              "69position", "mix", None,
              "Dedicated 69.",
              ("NSFW_GIF", "69", "~3M", "If dedicated is stale.")),
            T("legs_spread", "Legs spread / anatomy expose",
              "Legs parted so vulva/anus read. Solo or partnered. Still pose.",
              "Hip abduction. Standing, supine, or squat.",
              "Hold.",
              "Hips + both legs + torso. Drop macros.",
              "spreading", "still", None,
              "Dedicated parted-leg stills."),
            T("hanging_breasts", "Hanging breasts",
              "Torso inverted or parallel so breasts hang. Combine with all_fours or bent_over.",
              "Chest dropped, breasts pendulous.",
              "Swing on each thrust or crawl step.",
              "Side or 3/4 low enough to see hang + hips.",
              "thehangingboobs", "mix", None,
              "The camera, not the act. Pair with doggy/FDAU."),
        ],
    ),

    # =====================================================================
    dict(
        id="contact",
        label="Contact — what is touching",
        note="Stacks on any pose. doggy+anal is two ids, not a new pose.",
        topics=[
            T("vaginal", "Vaginal",
              "Penis, strap, or toy in the vagina. Default contact if unspecified.",
              "Whatever the pose is.",
              "Thrust / grind / bounce.",
              "Hips + insertion readable.",
              "whenitgoesin", "gif", None,
              "Insertion feed. Search the pose."),
            T("anal", "Anal",
              "Penis, strap, or toy in the anus. Usually doggy or prone.",
              "Same as the chosen rear pose.",
              "Often slower, deeper hold.",
              "Rear 3/4, hips + insertion.",
              "anal", "gif/vid", "~2.2M",
              "Largest anal feed."),
            T("cunnilingus", "Oral on her",
              "Mouth on her vulva. She receives.",
              "Her hips + legs are the sheet. Partner's head is a prop.",
              "Lick. Hold her hip drop or thigh spread.",
              "Her hips and both legs.",
              "cunnilingus", "mix", None,
              "Dedicated oral-on-her."),
            T("blowjob", "Blowjob / oral on him",
              "Her mouth on a penis. Pose is usually kneel_oral.",
              "See kneel_oral / deepthroat.",
              "Bob.",
              "Knees + spine + face.",
              "Blowjobs", "mix", "~2.4M",
              "Largest BJ feed."),
            T("rim", "Rimming",
              "Mouth on her anus. All-fours or sit-on-face.",
              "FDAU or facesit, hips to the tongue.",
              "Lick hold.",
              "Hips + anus + her torso.",
              "rimjob", "mix", None,
              "Largest dedicated rim feed."),
            T("handjob", "Handjob",
              "Her hands on a penis. Low pose value unless full body.",
              "Kneel, sit, or lie. Hands are the act.",
              "Stroke.",
              "Full body + hands. Skip hand macros.",
              "NSFW_GIF", "gif", "~3M",
              "Search handjob. Rarely a sheet by itself."),
            T("fingering", "Fingering",
              "Fingers in her vagina or anus. Solo or partnered.",
              "Usually supine, squat, or all-fours.",
              "In/out or come-hither.",
              "Hips + hand + torso.",
              "NSFW_GIF", "gif", "~3M",
              "Search fingering. Pair with legs_spread."),
            T("titfuck", "Titfuck",
              "Penis between her breasts. She is usually kneeling or he is on her chest.",
              "Torso-up, breasts around a shaft, face often in frame.",
              "Squeeze-stroke.",
              "Torso + breasts + face. Not a hip sheet.",
              "NSFW_GIF", "gif", "~3M",
              "Search titfuck / paizuri."),
            T("thighjob", "Thighjob / intercrural",
              "Penis between her closed thighs. No insertion.",
              "Thighs together, standing, missionary, or spoon.",
              "Thrust between thighs.",
              "Closed thighs + hips.",
              "NSFW_GIF", "gif", "~3M",
              "Search thighjob / intercrural / between thighs."),
            T("footjob", "Footjob",
              "Feet on a penis. She is usually sitting or lying, legs extended.",
              "Legs long, soles or arches on the shaft.",
              "Stroke with feet.",
              "Both legs + feet + her torso if you need a sheet.",
              "NSFW_GIF", "gif", "~3M",
              "Search footjob. Usually not a full-body sheet."),
            T("toy", "Toy / dildo",
              "A toy does the penetrating or the sitting. Strap is lesbian_strap / pegging.",
              "Whatever pose holds the toy.",
              "Toy stroke or ride.",
              "Toy + hips + her torso.",
              "OnAllFours", "mix", None,
              "Search dildo / toy inside the pose sub."),
            T("fist", "Fisting",
              "Hand inside vagina or anus. Hip splay.",
              "Wide hip abduction + forearm.",
              "In/out hold at the wrist.",
              "Hips + arm + torso.",
              "fisting", "mix", None,
              "Dedicated."),
            T("strap", "Strap / harness (contact)",
              "A harnessed phallus. Who wears it is pegging or lesbian_strap.",
              "Harness on a female hips.",
              "Thrust.",
              "Harness + both bodies.",
              "strapon", "mix", None,
              "Largest strap feed. Child acts pick who receives."),
        ],
    ),

    # =====================================================================
    dict(
        id="act",
        label="Act — named topology (people + orifices + motion)",
        note="These are the nouns a storyboard uses. Each one implies a config and usually a pose.",
        topics=[
            T("spit_roast", "Spit roast / split roast",
              "She between two partners: oral + rear (or oral + front). Same act, both spellings. AKA Eiffel if they high-five.",
              "Three-body line. Her spine end to end.",
              "Two cycles. Hold a still line.",
              "Her whole body + both partners.",
              "spitroast", "mix", None,
              "Dedicated. Do not use r/Threesome (mixed).",
              ("mfm", None, None, "More volume. Filter for the oral+rear line.")),
            T("sandwich", "Sandwich",
              "Two partners, one in front and one behind, no required oral. She is the filling.",
              "Two locks at her hips, chests on both sides.",
              "Two thrust cycles, often DP.",
              "Her torso between two bodies.",
              "mfm", "mix", None,
              "Search sandwich / airtight / DP. Distinct from spit_roast (no oral required)."),
            T("double_penetration", "DP (vaginal + anal)",
              "Two penetrations, one vaginal and one anal. The default 'DP'.",
              "Hips splayed to take two.",
              "Two thrust cycles.",
              "Hips + both entries + her torso.",
              "doublepenetration", "mix", None,
              "Dedicated DP."),
            T("double_vaginal", "Double vaginal",
              "Two in the vagina. Rarer. Wider hip splay than DP.",
              "Extreme abduction, two shafts one hole.",
              "Two cycles in one hole.",
              "Hips + both shafts + torso.",
              "doublepenetration", "mix", None,
              "Search DVP / double vaginal."),
            T("double_anal", "Double anal / DAP",
              "Two in the anus.",
              "Same as DP with both rear.",
              "Two rear cycles.",
              "Rear hips + both entries.",
              "doubleanal", "mix", None,
              "Dedicated DAP. Thin. Else search DAP in r/doublepenetration."),
            T("airtight", "Airtight",
              "Oral + vaginal + anal at once. Three occupied holes.",
              "Spit-roast line plus a second penetration.",
              "Three cycles.",
              "Her full body with all three contacts.",
              "AirTight", "mix", None,
              "Only feed that defines this topology."),
            T("triple_penetration", "Triple penetration",
              "Three penetrations. Usually airtight, sometimes two in one hole + a third.",
              "Same as airtight or DP+oral with extras.",
              "Three cycles.",
              "All three contacts + her torso.",
              "AirTight", "mix", None,
              "Search triple. Overlaps airtight."),
            T("threesome_369", "369",
              "Two people in 69, a third penetrates one of them (usually doggy into the woman on top).",
              "69 stack + a third body at the hips.",
              "Lick + thrust.",
              "The 69 stack and the third lock.",
              "NSFW_GIF", "gif", "~3M",
              "Search 369. Niche."),
            T("double_cowgirl", "Double cowgirl",
              "FFM: one woman rides him, the other sits on his face (or both ride in turn).",
              "Two female riding/sitting skeletons on one supine male.",
              "Two bounce/grind cycles.",
              "Both women complete.",
              "Threesome", "mix", "~1.1M",
              "Search double cowgirl / FFM ride."),
            T("scissoring", "Scissoring / tribbing",
              "Two women, legs locked, vulva-on-vulva or thigh grind. The girl-on-girl pose.",
              "Two female hip girdles interlocked.",
              "Grind cycle.",
              "Both spines + locked legs.",
              "scissoring", "mix", None,
              "Dedicated. Do not use r/lesbians for this pose."),
            T("lesbian", "Lesbian / girl-on-girl (parent)",
              "Two+ women, full-body contact. Filter kissing-only. Child acts: scissoring, lesbian_strap, lesbian_squirt.",
              "Dual female.",
              "Depends on child.",
              "Both bodies complete.",
              "lesbians", "mix", "~1.8M",
              "Largest girl-on-girl porn sub."),
            T("lesbian_strap", "Lesbian strap-on",
              "One woman strapped, fucking another. All-fours, missionary, or standing.",
              "Two female bodies + harness.",
              "Thrust. Same as doggy/missionary with a harness.",
              "Both bodies + the strap.",
              "strapon", "mix", None,
              "Largest strap feed. Pegging-him is disallowed there.",
              ("LesbianPegging", None, None, "If you need lesbian-only.")),
            T("lesbian_squirt", "Lesbian squirt",
              "Two+ women, at least one squirting.",
              "Dual female + gush.",
              "Lick/scissor/strap + jet.",
              "Both bodies + the jet.",
              "LesbiansSquirtingNSFW", "gif/vid", None,
              "Only feed that defines girl-on-girl + gush."),
            T("pegging", "Pegging",
              "She wears a harness and penetrates a man. Not lesbian.",
              "She standing or kneeling behind a body, harness on.",
              "She thrusts.",
              "Her full body + harness + his hips.",
              "pegging", "mix", "~547k",
              "Dedicated her-on-him strap."),
            T("fucklicking", "Fucklicking / licked while fucked",
              "A mouth on her (or on the insertion) while she is being penetrated.",
              "Sex pose plus a second head at the hips.",
              "Thrust + lick together.",
              "Her full body + licking head + penetrating partner.",
              "FFMFucklick", "mix", None,
              "Subscribed. Named fucklick feed — during-sex, not cleanup.",
              ("NSFW_GIF", 'fucklicking OR "eating her out while"', "~3M", "If the dedicated sub is thin.")),
            T("creampie_cleanup", "Creampie cleanup",
              "A mouth cleaning cum out of her after a creampie.",
              "Doggy or missionary aftermath, second head at the hips.",
              "Lick the leak.",
              "Drip + tongue + her hips.",
              "CreampieCleanUp", "mix", None,
              "Highest-signal cleanup feed.",
              ("MenEatingCreampies", None, None, "1-on-1, less cuck-tagged.")),
            T("ass_to_mouth", "Ass to mouth / ATM",
              "Penis or toy goes from her anus to a mouth (hers or a partner's).",
              "Usually doggy then kneel, or a head at the hips.",
              "Pull-out + mouth. Transition.",
              "The pull-out and the mouth in one beat if possible.",
              "NSFW_GIF", "gif", "~3M",
              "Search ATM / ass to mouth. Tight crops common."),
            T("snowball", "Snowball",
              "Cum passed mouth-to-mouth.",
              "Two faces. Low pose value.",
              "Transfer.",
              "Skip unless her full kneel reads.",
              "NSFW_GIF", "gif", "~3M",
              "Search snowball. Face-heavy."),
            T("freeuse", "Freeuse / used mid-task",
              "Used while occupied: sink, chores, sleep-pose, standing at a counter.",
              "Task pose + penetration.",
              "She stays in the task. He moves.",
              "Task + sex in one frame.",
              "freeuse", "mix", "~2.0M",
              "Largest mid-task sex feed."),
            T("rough", "Rough / pinned / folded",
              "Hair, slap, pin, fold. A force overlay on another pose.",
              "Base pose plus locked arms or folded legs.",
              "Hard thrust, pin holds.",
              "The pin: arms, hair, or fold readable.",
              "SheLikesItRough", "gif", "~1.7M",
              "Largest rough-sex gif feed."),
        ],
    ),

    # =====================================================================
    dict(
        id="finish",
        label="Finish / fluid / aftermath",
        note="A beat after or during the act. Combine with a pose. Do not use a finish id as the only pose.",
        topics=[
            T("creampie", "Creampie / internal finish",
              "He finishes inside. 1-on-1 or group.",
              "Whatever the sex pose is at finish.",
              "Finish hold, then optional pull-out.",
              "Full-seat finish. Hips + torso.",
              "creampies", "mix", "~1.4M",
              "Core creampie feed."),
            T("creampie_flow", "Creampie flowing out",
              "Cream leaking or being pushed out after. The drip is the act.",
              "Usually doggy or missionary, partner pulled back.",
              "Drip, push-out, overflow.",
              "The flow, hips still in the sex pose.",
              "CreamPieFlowingOut", "mix", None,
              "Exact act.",
              ("creampiegifs", "flowing OR leaking OR drip", None, "Motion leak.")),
            T("anal_creampie", "Anal creampie",
              "Internal anal finish + optional leak.",
              "Prone or doggy.",
              "Finish, then drip.",
              "Rear hips + drip.",
              "anal", "gif/vid", "~2.2M",
              "Search anal creampie. Dedicated AnalCreampie is smaller."),
            T("breeding_supine", "Breeding / on-back legs open",
              "On her back, legs open, 'breed' framing. Adult fertility look — not underage.",
              "Supine, knees wide, pelvis tilted up.",
              "Deep seat, hold.",
              "Torso + both legs + pelvis.",
              "BreedingMaterial", "mix", None,
              "The pose+finish together."),
            T("facial", "Facial",
              "Finish on her face. Usually kneel or supine look-up.",
              "Kneel_oral or missionary look-up.",
              "The shot.",
              "Face + torso + knees. Skip face-only.",
              "NSFW_GIF", "gif", "~3M",
              "Search facial. Huge dumps are too broad (r/cumsluts)."),
            T("body_cum", "Body cumshot",
              "Finish on breasts, belly, ass, or back. Not a facial, not internal.",
              "Whatever pose presents the target surface.",
              "The shot.",
              "The surface + her torso.",
              "NSFW_GIF", "gif", "~3M",
              "Search cum on tits / belly / ass."),
            T("bukkake", "Bukkake",
              "Many finish on her face/body. Kneel in a circle. Overlay on blowbang.",
              "Kneel/sit, many shafts, splash.",
              "Many shots.",
              "Knees + torso. Skip face-only.",
              "bukkake", "mix", "~456k",
              "Dedicated splash. Pose is kneel."),
            T("throatpie", "Throatpie",
              "He finishes in her throat / mouth, often swallowed or leaking from lips.",
              "Deepthroat or kneel_oral at full seat.",
              "Finish hold.",
              "Neck + torso + knees.",
              "deepthroat", "gif", "~1.5M",
              "Search throatpie / oral creampie."),
            T("squirt", "Squirt / gush",
              "Female ejaculation / gush. Mixes pee. Judge the picture.",
              "Usually supine or all-fours, thighs parted.",
              "Jet or gush. One frame is the sheet.",
              "The jet. Hips + thighs in frame.",
              "squirting", "mix", "~2.1M",
              "Largest squirt community. ~950 posts/week."),
            T("squirt_while_fucked", "Squirt during penetration",
              "Gush while being fucked. Doggy and cowgirl dominate.",
              "Underlying sex pose plus the jet.",
              "Thrust + gush on the same beat.",
              "Insertion + jet in one frame.",
              "SquirtWhileFucked", "gif", None,
              "Defines squirt-during-sex. Do not substitute r/squirting."),
            T("gape", "Gape",
              "Open hole after anal or toys. Anatomy after the pose is already right.",
              "Usually FDAU or doggy, partner pulled back.",
              "Hold the open.",
              "Rear hips + gape + torso.",
              "gaping", "mix", None,
              "Dedicated gape."),
            T("distension", "Distension / bulge",
              "Belly or hole stretch from a large insertion. Visible silhouette.",
              "Standing or supine with a bulge.",
              "Seat and hold.",
              "Profile so the bulge reads.",
              "distension", "mix", "~511k",
              "Dedicated stretch silhouette."),
        ],
    ),

    # =====================================================================
    dict(
        id="movement",
        label="Movement — the beat inside a pose",
        note="These are not poses. They tell the clip what to do in the hold.",
        topics=[
            T("insertion", "Insertion beat",
              "The first-thrust / when-it-goes-in moment.",
              "Whatever pose is about to lock.",
              "Entry. One frame.",
              "Tip-to-seat, hips + both bodies.",
              "whenitgoesin", "gif", None,
              "Dedicated insertion moment."),
            T("bounce", "Bounce / ride cycle",
              "She moves up and down. Cowgirl family.",
              "See cowgirl / reverse_cowgirl / squat_ride.",
              "Up-down. Hold peak height or peak seat.",
              "Peak bounce, knees planted.",
              "SheFucksHim", "gif", "~2.5M",
              "The riding dump is the bounce library."),
            T("grind", "Grind",
              "Hips circle or rock without a full stroke. Lotus, cowgirl lean, facesit, scissor.",
              "Connected hips, small motion.",
              "Circle / rock.",
              "Hips locked, torso readable.",
              "SheFucksHim", "gif", "~2.5M",
              "Search grind."),
            T("thrust", "Thrust cycle",
              "He moves, she is the brace. Doggy, missionary, standing, prone.",
              "Her brace pose.",
              "In-out. Hold peak hip crash.",
              "His lock + her brace.",
              "Doggystyle_NSFW", "gif", None,
              "Any penetration gif dump. Doggy is the type specimen."),
            T("look_back", "Look-back",
              "Head rotates to camera over the shoulder. Overlay on doggy, FDAU, reverse cowgirl, bent.",
              "Base pose + rotated head.",
              "Hold the look.",
              "Face and hips in one frame.",
              "frombehind", "mix", None,
              "Look-back lives here."),
            T("crawl", "Crawl",
              "She moves forward on all fours. Present without a locked partner.",
              "all_fours in motion.",
              "Step the hands, then the knees.",
              "Mid-step, all four points visible.",
              "OnAllFours", "mix", None,
              "Pose-only crawl."),
            T("swap", "Partner swap",
              "Train beat: one partner leaves, the next locks.",
              "Same pose, new partner.",
              "The exchange.",
              "Old lock releasing or new lock seating.",
              "runatrain", "mix", None,
              "Sequential by definition."),
        ],
    ),

    # =====================================================================
    dict(
        id="camera",
        label="Camera",
        note="Lens, not pose. Combine with a pose id.",
        topics=[
            T("plowcam", "Plowcam / floor camera",
              "Lens under or between during sex. Looking up at hips.",
              "Whatever pose is above the lens.",
              "Thrust toward camera.",
              "Low, hips large, torso receding.",
              "nsfw_plowcam", "gif", None,
              "Dedicated under-angle."),
            T("pov", "POV",
              "Camera is a participant. Usually his eyes. She looks into lens.",
              "Whatever pose faces the lens.",
              "Depends.",
              "Her face + the act. Watch for face-only.",
              "NSFW_GIF", "gif", "~3M",
              "Search POV + the pose. Too broad to be a pose source."),
            T("rear", "Rear camera",
              "Lens behind her hips. FDAU, doggy, reverse cowgirl, bent.",
              "Back, hips, soles or look-back.",
              "Depends.",
              "Hips fill the frame, torso recedes.",
              "frombehind", "mix", None,
              "Rear camera standing or bent."),
            T("side_3qtr", "Side / three-quarter",
              "The default storyboard camera. Full skeleton.",
              "Whole body, 3/4.",
              "Depends.",
              "Head to feet.",
              "NSFW_GIF", "gif", "~3M",
              "Prefer this over macros in any sub."),
        ],
    ),

    # =====================================================================
    dict(
        id="anatomy",
        label="Anatomy — texture after pose QC",
        note=(
            "Not a pose. Sample shape/lighting of vulva and anus after the skeleton "
            "already passed pose QC (cat face, both arms, source skin, tail origin "
            "above the anus). Retone Lab a,b from looking-back.jpg + standing.jpg. "
            "Never as image1 or as a person-plate in image2."
        ),
        topics=[
            T("rear_anatomy", "Rear vulva / perineum from behind",
              "From-behind view of vulva + perineum + anus. All-fours or bent look-back. Tail origin sits above the anus.",
              "Hips toward camera, cheeks parted, both holes readable. Pose already accepted.",
              "Hold. No act required.",
              "Lit cleft. Trim panties if present. Discard the person.",
              "rearpussy", "still", "~1.2M",
              "Named rear-pussy stills. Trim garments.",
              ("Pussy_From_Behind", None, "~96k", "Look-back rear vulva sibling.")),
            T("vulva_closeup", "Vulva close-up / labia shape",
              "Front or 3/4 close-up of human-shaped vulva. Innie/outie/spread. Shape library only.",
              "Crotch crop is allowed here. Not a body pose.",
              "None.",
              "Readable labia. Adult 18+ only.",
              "GodPussyv2", "still", "~87k",
              "Live r/godpussy. Certified close-ups.",
              ("PussiesCloseUp", None, "~208k", "Shaved close-up dump.")),
            T("anus_closeup", "Anus / tail-origin close-up",
              "Anus and the skin just above it — where her tail must start. Not a gape act.",
              "Rear crop. Coccyx / top of cleft visible.",
              "None.",
              "Closed or softly open anus, tail-root zone lit.",
              "GodAsshole", "still", "~815k",
              "High-volume anus stills.",
              ("asshole_closeup", None, "~401k", "Tight detail.")),
        ],
    ),

    # =====================================================================
    dict(
        id="overlay",
        label="Overlay — body class and scene force",
        note="Never a pose by itself. Search the topic id on the overlay source.",
        topics=[
            T("anthro", "Anthro / yiff",
              "Drawn furry sex. Pose library for her class. Identity still comes from her photos.",
              "Whatever act you searched. Discard the character.",
              "Search the pose/act id as a tag.",
              "Readable anthro skeleton. Never as image2 person-plate.",
              "yiff", "still", None,
              "Main furry porn.",
              ("lesbianyiff", "lesbian OR scissor OR strap", None, "Girl-on-girl anthro.")),
            T("public", "Public",
              "Sex where she can be seen. Standing, wall, car, outdoors. Blurry phones.",
              "Usually standing_sex or bent_over.",
              "Quiet, hurried.",
              "Sharp full-body only.",
              "holdthemoan", "gif", "~2.1M",
              "Largest public-ish standing feed."),
            T("bondage", "Bondage",
              "Rope, cuffs, hogtie, spread-eagle restraints. Geometry is the tie + a base pose.",
              "Base pose with locked limbs.",
              "She cannot move. He does.",
              "The tie + her full body.",
              "NSFW_GIF", "gif", "~3M",
              "Search bondage + the pose. r/Bondage is mixed discussion."),
        ],
    ),
]

NOT_IN_CATALOG = [
    "Casting / body: MILF, GILF, teen, petite, PAWG, BBW, ebony, asian, latina, redhead — pick a model, not an act.",
    "Production: amateur, gonzo, POV-as-genre, 60fps, VR, hentai-as-genre, OnlyFans — pipeline, not a pose.",
    "Lifestyle tags that are just MFM with extra text: hotwife, cuckold, swinging. Use mfm + the pose.",
    "Named micro-variations that do not change the skeleton: CAT, lunging cowgirl, restrained doggy, little dipper, waterfall, bouncing spoon, rusty trombone, seventh posture.",
    "Male-only: frot, docking, circle jerk as the sheet. Out of scope unless she is in frame.",
]


def rec(t):
    p = t["primary"]
    out = {
        "id": t["id"],
        "label": t["label"],
        "definition": t["definition"],
        "skeleton": t["skeleton"],
        "movement": t["movement"],
        "hold_frame": t["hold_frame"],
        "primary": {
            "sub": p[0],
            "media": p[1],
            "members": p[2],
            "why": p[3],
        },
        "fallback": None,
    }
    if t["fallback"]:
        f = t["fallback"]
        out["fallback"] = {
            "sub": f[0],
            "search": f[1],
            "members": f[2],
            "why": f[3],
        }
    return out


def write_json():
    families = []
    topics_flat = []
    for fam in FAMILIES:
        ftopics = [rec(t) for t in fam["topics"]]
        for t in ftopics:
            t["family"] = fam["id"]
            if t["id"] in VARIANTS:
                t["variants"] = VARIANTS[t["id"]]
            topics_flat.append(t)
        families.append({
            "id": fam["id"],
            "label": fam["label"],
            "note": fam["note"],
            "topic_ids": [t["id"] for t in fam["topics"]],
        })
    doc = {
        "_readme": README,
        "updated": "2026-08-15",
        "compose": "configuration × pose × contact × act × finish × movement × camera [× overlay]  |  anatomy after pose QC",
        "hard_excludes": HARD_EXCLUDES,
        "not_in_catalog": NOT_IN_CATALOG,
        "gif_dump": {"sub": "NSFW_GIF", "members": "~3M"},
        "index": "https://www.reddit.com/r/NSFW411/wiki/index/",
        "aliases": ALIASES,
        "variants": VARIANTS,
        "profile_activity": PROFILE_ACTIVITY,
        "families": families,
        "topics": topics_flat,
    }
    path = OUT / "reddit-pose-catalog.json"
    path.write_text(json.dumps(doc, indent=2) + "\n")
    return path, doc


def write_md():
    n = sum(len(f["topics"]) for f in FAMILIES)
    parts = [
        "# Scene vocabulary — configs, poses, acts, finishes",
        "",
        "Operator catalog for Meow P. **Adult 18+ only.** Updated 2026-08-15.",
        "",
        "A scene is composed, not named:",
        "",
        "`configuration × pose × contact × act × finish × movement × camera [× overlay]`",
        "",
        "Example: `mfm` + `doggy` + `anal` + `spit_roast` + `creampie_flow` + `thrust` + `rear`.",
        "",
        f"{n} distinct topic ids in {len(FAMILIES)} families. "
        f"{len(ALIASES)} aliases map tube/storyboard names onto those ids.",
        "",
        "Use: resolve the name through **Aliases** → open the topic → scrub to `hold_frame`",
        "→ extract skeleton / depth / camera → **discard the pixels**.",
        "",
        "## Hard excludes",
        "",
    ]
    for x in HARD_EXCLUDES:
        parts.append(f"- {x}")
    parts += ["", "## Not in this catalog (on purpose)", ""]
    for x in NOT_IN_CATALOG:
        parts.append(f"- {x}")

    parts += [
        "",
        "## Variants (topic + posture)",
        "",
        "A scene row is `topic` + optional `variant`. Example: `squirt` + `seated`.",
        "",
        "| topic | variants |",
        "|---|---|",
    ]
    for tid, vs in VARIANTS.items():
        parts.append(f"| `{tid}` | {', '.join(vs)} |")

    parts += [
        "",
        "## u/SouthFloridaCouple (public activity, not subscriptions)",
        "",
        "Reddit does **not** publish another user's subscribed list. What follows is",
        "their public posts (12) and comments (100) from arctic-shift, 2026-08-15.",
        "",
        "| sub | maps to | why |",
        "|---|---|---|",
    ]
    for row in PROFILE_ACTIVITY["pose_useful"]:
        parts.append(f"| r/{row['sub']} | `{row['maps_to']}` | {row['why']} |")
    parts += ["", "Ignored from that profile:"]
    for x in PROFILE_ACTIVITY["not_pose"]:
        parts.append(f"- {x}")

    parts += [
        "",
        "## Families",
        "",
        "| family | what it answers |",
        "|---|---|",
        "| `configuration` | Who is in the scene? MFM vs FMF vs FFM vs foursome vs orgy |",
        "| `pose` | What is her skeleton? |",
        "| `contact` | What is touching? vaginal / anal / oral / strap / fist |",
        "| `act` | Named topology: spit roast, DP, scissoring, fucklicking |",
        "| `finish` | How it ends: creampie, flow, squirt, facial, gape |",
        "| `movement` | The beat: bounce, thrust, insertion, look-back, swap |",
        "| `camera` | Lens: plowcam, rear, POV, 3/4 |",
        "| `overlay` | Force / body class: anthro, public, bondage |",
        "| `anatomy` | Vulva/anus texture AFTER pose QC. Never image2. |",
        "",
        "## Cheat sheet",
        "",
        "| id | family | primary |",
        "|---|---|---|",
    ]
    for fam in FAMILIES:
        for t in fam["topics"]:
            mem = t["primary"][2]
            prim = f"r/{t['primary'][0]}" + (f" ({mem})" if mem else "")
            parts.append(f"| `{t['id']}` | {fam['id']} | {prim} |")

    parts += [
        "",
        "## Aliases",
        "",
        "Any name on the left is the topic on the right. Use the topic id in a scene row.",
        "",
        "| name you might type | topic id |",
        "|---|---|",
    ]
    for k in sorted(ALIASES, key=lambda s: (ALIASES[s], s)):
        parts.append(f"| {k} | `{ALIASES[k]}` |")

    for fam in FAMILIES:
        parts += [
            f"## {fam['label']}",
            "",
            fam["note"],
            "",
        ]
        for t in fam["topics"]:
            p = t["primary"]
            mem = f" · {p[2]}" if p[2] else ""
            parts += [
                f"### `{t['id']}` — {t['label']}",
                "",
                f"primary r/{p[0]} ({p[1] or 'mix'}{mem})",
                "",
                t["definition"],
                "",
                f"- skeleton: {t['skeleton']}",
                f"- movement: {t['movement']}",
                f"- hold frame: {t['hold_frame']}",
                f"- why this sub: {p[3]}",
            ]
            if t["fallback"]:
                f = t["fallback"]
                search = f" · search `{f[1]}`" if f[1] else ""
                fmem = f" · {f[2]}" if f[2] else ""
                parts.append(f"- fallback: r/{f[0]}{search}{fmem} — {f[3]}")
            parts.append("")

    parts += [
        "## Notes",
        "",
        "- **MFM ≠ MMF.** MFM is two men on her, no MM. MMF is bisexual, lucky Pierre.",
        "- **FFM ≠ FMF.** FFM = the women interact. FMF = man in the middle, women on him.",
        "- **Foursome** is a count. Pick `mfmf`, `mmmf`, or `fffm`.",
        "- **Split roast** = **spit roast**. One topic.",
        "- **Scissoring** is lesbian. **side_scissor** is hetero pretzel. Different skeletons.",
        "- Cast tags (MILF, ethnicity, amateur) are not acts. Do not add them.",
        "- Do not scrape. Manual pick → skeleton → her keeper.",
        "",
    ]
    path = OUT / "reddit-pose-catalog.md"
    path.write_text("\n".join(parts))
    return path


def main():
    global OUT
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--out", default=str(REPO / "anchor5"),
                    help="directory for reddit-pose-catalog.json/.md (default: anchor5/)")
    args = ap.parse_args()
    OUT = Path(args.out)
    OUT.mkdir(parents=True, exist_ok=True)
    jp, doc = write_json()
    mp = write_md()
    n = len(doc["topics"])
    by = {}
    for t in doc["topics"]:
        by.setdefault(t["family"], 0)
        by[t["family"]] += 1
    print(f"wrote {mp} and {jp}")
    print(f"topics {n} aliases {len(doc['aliases'])}")
    for k, v in by.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
